version: '3.7'
networks:
  orchestration:
services:
  docker-api:
    image: 'nginx:1.16.1'
    ports:
    - '80:3000'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      orchestration:
        aliases:
        - docker.api